### ISSUE TITLE
Change API to specify duration for each fragment

### ISSUE THREAD

**Issue by avsd** [WatchTheDocs/watchthedocs#9]
Apparently, Amazon Polly supports speech marks now. You can get JSON with exact time marks where each word or sentence starts.

Therefore, we don't need to guess based on number of syllables anymore. Instead, we need to add support of speech marks in `.watch` file.

So, instead of this:

```yaml
    duration: 10000
    audio:
      position: 0
      duration: 7000
    say:
      - "The second slide has a title and one paragraph."
      - "It also has a voice-over."
```

we will have this:

```yaml
    duration: 10000
    audio:
      -
        start: 0
        duration: 4000
      -
        start: 4100
        duration: 5000
     say:
       - "The second slide has a title and one paragraph."
       - "It also has a voice-over."
```
